version: "3"

x-kafka-common: &kafka-common
  image: bitnami/kafka:2.6.0
  environment: &kafka-common-env
    KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ALLOW_PLAINTEXT_LISTENER: "yes"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
    KAFKA_INTER_BROKER_LISTENER_NAME: "CLIENT"
    KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_CFG_LOG_DIRS: "/opt/kafka/data/"
  depends_on:
    - zookeeper
  networks:
    - kafka-cluster

networks:
  kafka-cluster:
    name: kafka-cluster
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-cluster

  kafka1:
    <<: *kafka-common
    container_name: kafka1
    ports:
      - '9093:9093'
    volumes:
      - ./data/kafka1:/opt/kafka/data
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_LISTENERS: "CLIENT://:9092,EXTERNAL://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://kafka1:9092,EXTERNAL://localhost:9093"

  kafka2:
    <<: *kafka-common
    container_name: kafka2
    ports:
      - '9094:9094'
    volumes:
      - ./data/kafka2:/opt/kafka/data
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_LISTENERS: "CLIENT://:9092,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://kafka2:9092,EXTERNAL://localhost:9094"

  kafka3:
    <<: *kafka-common
    container_name: kafka3
    ports:
      - '9095:9095'
    volumes:
      - ./data/kafka3:/opt/kafka/data
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_LISTENERS: "CLIENT://:9092,EXTERNAL://:9095"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://kafka3:9092,EXTERNAL://localhost:9095"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092,kafka2:9092,kafka3:9092
    depends_on:
      - kafka1
    networks:
      - kafka-cluster
